<?xml version="1.0" encoding="utf-8" standalone="yes"?><rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom"><channel><title>Error on Gromit.Blog</title><link>https://gowoonsori.com/categories/error/</link><description>Recent content in Error on Gromit.Blog</description><generator>Hugo -- gohugo.io</generator><language>ko-kr</language><lastBuildDate>Sun, 02 May 2021 21:17:07 +0900</lastBuildDate><atom:link href="https://gowoonsori.com/categories/error/index.xml" rel="self" type="application/rss+xml"/><item><title>Spring Security Cors Mapping Error</title><link>https://gowoonsori.com/blog/error/springsecurity-cors/</link><pubDate>Sun, 02 May 2021 21:17:07 +0900</pubDate><guid>https://gowoonsori.com/blog/error/springsecurity-cors/</guid><description>CORS 란? Cross-Stie HTTP Requests의 약자로 한 도메인이 다른 도메인의 자원을 사용하는 것을 의미하는데, chrome cors 기본정책이 strict-origin-when-cross-origin으로 Same Origin에 대해서만 자원을 사용하도록 제한되어 있다. 여기서 Same-Origin이란 호스트명, 프로토콜, 포트가 같은 도메인을 말한다. Front</description></item><item><title>Intellij 시작시 바로 꺼지는 Error</title><link>https://gowoonsori.com/blog/error/intellij-down-error/</link><pubDate>Thu, 15 Apr 2021 12:12:22 +0900</pubDate><guid>https://gowoonsori.com/blog/error/intellij-down-error/</guid><description>윈도우로 작업을 위해 IDE를 실행시켜보면 아래와 같은 에러가 발생하며 IntelliJ뿐만 아니라 Jetbrain사의 모든 IDE들이 실행이 안되는데 매번 어떻게 해결했더라 기억을 되짚고 그때마다 여러 글을 뒤져보는게 힘들어 기록을 위해 작성한다. Internal error. Please refer to https://jb.gg/ide/critical-startup-errors java.util.concurrent.CompletionException: java.net.BindException: Address already in use: bind at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1702) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668) at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665) at java.base/java.security.AccessController.doPrivileged(Native Method) at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665) at java.base/java.lang.Thread.run(Thread.java:834) Caused by: java.net.BindException: Address already in</description></item><item><title>@OneToMany 관계시 발생한 에러</title><link>https://gowoonsori.com/blog/error/onetomanyerror/</link><pubDate>Sun, 11 Apr 2021 20:51:45 +0900</pubDate><guid>https://gowoonsori.com/blog/error/onetomanyerror/</guid><description>JPA의 구현체인 hiberante를 이용해서 엔티티간의 상속관계를 설정하고 처음 사용해보는데 발생한 에러인 A collection with cascade=&amp;ldquo;all-delete-orphan&amp;rdquo; was no longer referenced by the owning entity instance 문제 해결한 방법을 기록하려고 한다. User의 엔티티와 Customer엔티티간의 1:N 양방향 연관관계를 맺기 위해 User에는 @OneToMany를 Customer에는 @ManyToOn</description></item></channel></rss>